### ISSUE TITLE
Wrong depth for orthogonal camera (not perspective) in Volume + PolyData rendering

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#2647] opened 2022-11-29 22:43 UTC
### High-level description
I wanted to perform volume rendering for a volume and a sphere source (not a requirement to be sphere, but just as a polyData example). It works as expected for Perspective camera but not orthogonal camera. Is there a bug? or limitation? can you please guide me how I can fix this?

![image](https://user-images.githubusercontent.com/7490180/204664001-ca8521c9-839e-4a97-b732-30604603e80e.png)

### Detailed Behaviour
Manipulating the camera for parallel projection, sometimes it is correctly behind the chest wall, but sometimes it is not, so this looks to me like a bug than limitation (?)

### Steps to reproduce

I created a codesandbox, you can toggle parallel projection in line 119 and 120

https://codesandbox.io/s/volume-polydata-glvzp7?file=/src/index.js

### Expected behavior
To both works the same.

### Environment
- **vtk.js**:  25.1.3
- **OS**: Web
- **Browser**: Chrome

**Comment by finetjul** [comment] 2022-11-30 06:30
Could you create spheres at the 8 corners of the volume to understand what kind of "transform" seem to happen?

**Comment by finetjul** [comment] 2022-11-30 06:32
It would also be interesting to try to VR a large checkerboard volume to see if lines stay parallel in the orthographic projection.

**Comment by sedghi** [comment] 2022-11-30 15:50
Thanks @finetjul 

I edited the [example in codesandbox](https://codesandbox.io/s/volume-polydata-glvzp7?file=/src/index.js) and here are the results

# CT Volume Data
### Perspective Camera

![image](https://user-images.githubusercontent.com/7490180/204843543-4fcf214c-eebf-423b-b94d-d9c5ce0899d8.png)

### Parallel Projection

![image](https://user-images.githubusercontent.com/7490180/204843611-8b2453a9-09fa-4dc2-8d81-08e61047f41e.png)


# Checkboard 
The data is from [here](https://github.com/Kitware/vtk-js-datasets/tree/327e119172417034f3165d1f8d066cf338e032b5/data/vti/syntheticSlicesData.vti) that I contributed before, and description and screenshots are [here](https://github.com/Kitware/vtk-js/issues/1936#issuecomment-857318425)

### Perspective Camera

![image](https://user-images.githubusercontent.com/7490180/204843672-6ce04631-02b1-4399-92ea-ec29fc176636.png)

### Parallel Projection

![image](https://user-images.githubusercontent.com/7490180/204843721-3c187daf-d89c-4fb5-ac3a-581775e724a5.png)

**Comment by sedghi** [comment] 2022-12-06 14:52
Based on further investigation, this seems to be a problem in zBuffer implementation. 

First we tried to see if this is relevant to the opacity of the volume by changing the following line to lower the threshold for opaque [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/glsl/vtkVolumeFS.glsl#L1313), but same issue happened

```js
if (color.a > 0.99) { color.a = 1.0; break; }
```

After further look, it seems like the ZBuffer implementation in the OpenGL VolumeMapper here and source below 

```
FSSource = vtkShaderProgram.substitute(FSSource, '//VTK::ZBuffer::Impl', [
        'vec4 depthVec = texture2D(zBufferTexture, vec2(gl_FragCoord.x / vpWidth, gl_FragCoord.y/vpHeight));',
        'float zdepth = (depthVec.r*256.0 + depthVec.g)/257.0;',
        'zdepth = zdepth * 2.0 - 1.0;',
        'zdepth = -2.0 * camFar * camNear / (zdepth*(camFar-camNear)-(camFar+camNear)) - camNear;',
        'zdepth = -zdepth/rayDir.z;',
        'dists.y = min(zdepth,dists.y);',
      ]).result;
```

Is relevant to the problem, as in, if we change the last line from `dists.y = min(zdepth,dists.y);` and add some value to it like `dists.y = min(zdepth,dists.y) + 50.0` the sphere in the chest wall appears in the back of the volume. 

Based on my understanding opaque geometry populates the zTexture and the volume mapper uses it to decide where to put the far clipping plane. Am I right? 

@martinken Does this seem to be a bug to you?

**Comment by martinken** [comment] 2022-12-06 15:32
Yes, the issue is that it is only coded for perspective in line line 
```'zdepth = -2.0 * camFar * camNear / (zdepth*(camFar-camNear)-(camFar+camNear)) - camNear;',```

That needs to be an if statement based on if (cameraParallel == 1) and for parallel do a different equation. I think it would be

```zdepth = (zdepth + 1.0) * 0.5 * (camFar - camNear);```

but not tested.

**Comment by martinken** [comment] 2022-12-06 15:33
the (zdepth + 1.0)*0.5 is just undoing the line above so you could move that line into the else and simplify

**Comment by sedghi** [comment] 2022-12-06 22:46
@martinken It worked great! thanks a lot!

**Comment by daker** [comment] 2024-12-01 23:48
@sedghi can you close this if it has been fixed ?

**Closed** 2024-12-02 03:09 UTC
Labels: type: bug 🐞
