### ISSUE TITLE
Display bug with polydata file

### ISSUE THREAD

**Issue by ghost** [Kitware/vtk-js#771] opened 2018-06-22 13:18 UTC
Hi !

I have an issue with some normals which are not displayed correctly. It looks random and only appears when multiple .vtp files are loaded, but only one is visible with a representation of surface.

Opacity = 100, multiple files loaded, everything is visible (surface)
![viw-normal-opacity-100](https://user-images.githubusercontent.com/40494123/41778554-5b3e27b4-762f-11e8-9a3e-ab7e62f7eba4.png)

Opacity < 100, multiple files loaded, only one is visible (surface or surface+edge)
![viw-normal-opacity-30](https://user-images.githubusercontent.com/40494123/41778553-5b212c18-762f-11e8-821a-127d7196d0b2.png)

Opacity < 100, multiple files loaded, two are visible (surface + whatever)
![viw-fenetre_visbles-opacity-30](https://user-images.githubusercontent.com/40494123/41778555-5b5ae160-762f-11e8-9edb-008354947c24.png)

Are there any way to fix it, please ?

**Comment by jourdain** [comment] 2018-06-22 16:07
I think the issue is related to opacity and the fact that we don't have a depth peeling implementation yet.

As of today, we don't have a time frame for depth peeling support.

**Comment by floryst** [comment] 2021-04-23 15:38
This should be fixed in the WebGPU implementation. See #680

**Closed by floryst** 2021-04-23 15:38 UTC
Labels: Status: Duplicate
