### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1882] opened 2021-04-28 15:42 UTC
In version VTK v17.15.0, running VTK gives an error about regeneratorRuntime is missing.
Eventually, it can be fixed by installing the module, but I was wondering whether this was meant to happen?

**Screenshots**
![image](https://user-images.githubusercontent.com/47977073/116430927-902dd800-a847-11eb-98e5-03099fd808d6.png)

***vtk.js version:***
v17.15.0,

**Comment by jourdain** [comment] 2021-04-28 15:47
Duplicate of https://github.com/Kitware/vtk-js/issues/1862

**Comment by jourdain** [comment] 2021-04-28 15:49
@floryst can you look into it? If not, I'll try to get to it (not sure when).

**Comment by floryst** [comment] 2021-04-29 16:20
It seems that we've started adding `async` usages in our codebase (e.g. in [HardwareSelector](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/OpenGL/HardwareSelector/index.js#L361)). Babel preset-env transforms this into using regenerator runtime, requiring there be an `import 'regenerator-runtime/runtime' import somewhere in the code.

I don't think we should litter our code with `import 'regenerator-runtime/runtime', nor should we require users to bring in regenerator runtime if they don't use it. The most reasonable solution I can think of at the moment is to change existing code using `async` to returning promises.

**Comment by jourdain** [comment] 2021-05-03 14:37
Based on my experimentation MR, I would say that we are at a point where we need async in our code base.

**Comment by jourdain** [comment] 2021-05-03 14:37
That means consumer will need to `import 'regenerator-runtime/runtime';`

**Comment by daker** [comment] 2021-05-05 11:52
@jourdain in the case we need async the `useBuiltIns` in [.babelrc](https://github.com/Kitware/vtk-js/blob/master/.babelrc#L5) should usage or entry and core.js needs to be added.

https://babeljs.io/docs/en/babel-preset-env#usebuiltins

**Comment by floryst** [comment] 2022-03-02 20:35
This should only manifest in the `vtk.js` package, not the `@kitware/vtk.js` package. Recommendations:
- using `vtk.js`: import regenerator-runtime
- use `@kitware/vtk.js`

Closing for now, unless someone runs into this issue while following one of the above recommendations.

**Closed by floryst** 2022-03-02 20:35 UTC
Labels: type: bug 🐞, module: rendering, module: build
