### ISSUE TITLE
Is vtk.js supporting glTF file?

### ISSUE THREAD

**Issue by xuhenry** [Kitware/vtk-js#2441] opened 2022-06-01 15:33 UTC
### Need

Is vtk.js supporting glTF file?

**Comment by floryst** [comment] 2022-06-02 15:39
Duplicate of https://github.com/Kitware/vtk-js/issues/210. AFAIK we have draco support in vtk.js, but I don't think we have gltf at the moment.

@daker do you have any info on the gltf loader you mentioned in the aforementioned issue?

**Comment by daker** [comment] 2022-06-14 23:19
a draft PR to be reworked in #2479

**Comment by daker** [comment] 2024-11-17 17:27
An initial support for GLTF has been added, PBR requires WebGPU to work

https://kitware.github.io/vtk-js/examples/GLTFImporter/index.html?model=FlightHelmet&viewAPI=WebGPU

@floryst we can close the issue.

**Closed as completed** 2024-11-18 14:51 UTC
Labels: type: feature request 💡
