### ISSUE TITLE
Tube filter glitch

### ISSUE THREAD

**Issue by EmileSonneveld** [Kitware/vtk-js#1546] opened 2020-07-29 12:57 UTC
Hi, the tube filter in VTK.js behaves different than in c++.
In the following image, green is from VTK.js and gray from Paraview 5.8.0
![image](https://user-images.githubusercontent.com/2298426/88802001-c223e800-d1aa-11ea-87fc-e2e90b26c933.png)

Here is the code I used to reproduce in VTK.js: (the polydata line is embedded in the JS)
[tube-code.txt](https://github.com/Kitware/vtk-js/files/4994937/tube-code.txt)

Is this a problem with my poly data? code? vtk.js?
Thank you so much :)
Emile

**Comment by EmileSonneveld** [comment] 2020-07-29 12:59
@sankhesh do you know more? I saw that you contributed a lot to this :)

**Comment by sankhesh** [comment] 2020-07-29 14:34
@EmileSonneveld I'll take a look and let you know

**Comment by sankhesh** [comment] 2020-08-04 18:59
@EmileSonneveld I extracted the data from the text file you uploaded into a vtp file. Essentially just copying everything from the `VTKFile` section to the vtp file. 

Next, I ran it through the [tubesviewer](https://kitware.github.io/vtk-js/examples/TubesViewer/index.html) vtk-js application and paraview. The results are as in the screenshots below:

### TubesViewer
![Screenshot from 2020-08-04 14-53-48](https://user-images.githubusercontent.com/936354/89333381-dfe9c500-d662-11ea-84a8-736f0c4acb32.png)

### ParaView
![paraview-tube](https://user-images.githubusercontent.com/936354/89333400-e7a96980-d662-11ea-9765-4e18586173ff.png)

There is definitely an issue where the last line/cell is ignored by the vtk-js tube filter but I don't see the spike(?) that you show in the picture.

**Comment by EmileSonneveld** [comment] 2020-08-04 19:58
That spike is indeed mysterious. I had 2 exports with the spike on a different location. IIRC, I got it when exporting to STL, but not for VTI.

**Comment by sankhesh** [comment] 2020-08-04 20:18
>> IIRC, I got it when exporting to STL,

That would indicate an issue with the STL export and not tube filter.

**Comment by EmileSonneveld** [comment] 2020-08-26 16:28
Any fix possible for this one? Or an easy workaround?

**Comment by sankhesh** [comment] 2020-08-26 16:42
Since the issue is in the STL export code, you'd have to debug that. Or use a different geometry export format (e.g. OBJ).

**Comment by EmileSonneveld** [comment] 2020-08-26 17:53
The problem occurs before the STL export. STL export could have a second issue, but that can only be investigated after the tube filter is fixed.

**Comment by sankhesh** [comment] 2020-08-26 18:48
What is the issue in the tube filter? Based on https://github.com/Kitware/vtk-js/issues/1546#issuecomment-668769269 and https://github.com/Kitware/vtk-js/issues/1546#issuecomment-668795612, there is no spike in the output of the tube filter. It only happens when when you export to STL, right? Could you share more details about your workflow?

**Comment by EmileSonneveld** [comment] 2020-08-26 19:33
The problem you encountered in https://github.com/Kitware/vtk-js/issues/1546#issuecomment-668769269 is the real issue. The polyline is a closed loop, but when passing it trough the tube filter, there is a piece missing from the mesh. 😉

The spike is a different story. I did export the broken result out of VTK.js to investigate and compare with the result from VTK c++. The vtk.js export introduces a spike,  but I guess it will go away when fixing the initial issue.


Do you think the missing piece in the tube filter is fixable? 
If needed, we can make some contracts and pay for the development.

**Comment by sankhesh** [comment] 2020-08-26 19:42
Thanks for clarifying. Yes, we could fix the tube filter. Mind sharing your email address so we can discuss contracting off-list?

**Comment by EmileSonneveld** [comment] 2020-10-20 13:34
Older VTK.js versions don't have this problem. The regression is probably not because of a change in the tube filter code.
```json
"vtk.js": "^12.1.2", // No problem
"vtk.js": "^13.0.0", // Problem
"vtk.js": "^14.16.5", // Problem
```

**Comment by jourdain** [comment] 2020-10-20 14:19
FYI @floryst

**Comment by floryst** [comment] 2020-11-18 19:36
@EmileSonneveld  I cannot reproduce your versioning differences with what sankesh did in https://github.com/Kitware/vtk-js/issues/1546#issuecomment-668769269. v12.0.0, v12.1.2, and v13.0.0 all exhibit the issue in https://github.com/Kitware/vtk-js/issues/1546#issuecomment-668769269. 

I checked the commits as well, and none of them between v12.1.2 and v13.0.0 touch tube filter code.

**Comment by daker** [comment] 2021-04-29 17:19
@EmileSonneveld can you try the lastest version and see if does resolve the issue? then close the issue?

**Comment by daker** [comment] 2021-04-29 23:18
@EmileSonneveld here is the result with the latest fix of tube filter

![image](https://user-images.githubusercontent.com/878518/116629577-ce172300-a951-11eb-8bcd-6fbb882b63de.png)

@jourdain i propose to close the issue

**Closed** 2021-04-29 23:28 UTC
Labels: module: filters, status: confirmed, type: bug 🐞
