### ISSUE TITLE
Strange render artifacts at volume's min/max slice with InteractorStyleMPRSlice

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1150] opened 2019-07-18 23:19 UTC
I'm not sure if it's min or max, but at the extreme of one of the directions I consistently get strange cubic artifacting.

Examples: 
https://vue-vtkjs-viewport.netlify.com/#/example/basic
![image](https://user-images.githubusercontent.com/1474137/61497823-c43b5000-a975-11e9-8f62-81f831584c63.png)
Open any image, then mousewheel down.

https://kitware.github.io/vtk-js/examples/InteractorStyleMPRSlice.html
![image](https://user-images.githubusercontent.com/1474137/61497861-ea60f000-a975-11e9-9810-452de1c3d1b9.png)
Roll the slider all the way to the right.

Experiencing in Mac and Windows 10, Chrome and Mac Safari. 

Cannot reproduce on Firefox due to a separate issue, #1149.

UPDATE: Can reproduce on Firefox, separate issue only seems to affect my Vue project.

**Comment by aylward** [comment] 2021-04-23 17:48
Cannot reproduce on Firefox 87.0 or Chrome 90.0.4430.85 on Windows 10

**Comment by aylward** [comment] 2021-04-23 17:52
Cannot reproduce on Firefox or Chrome on Linux.

Closing until it resurfaces.

**Closed by aylward** 2021-04-23 17:52 UTC
Labels: Module: Interactor, Module: Rendering, Status: Triage, Type: Bug 🐞

**Comment by aylward** [comment] 2021-04-24 21:39
Clicking the link you provided works on Windows 10, Chrome.

![Example-Output](https://user-images.githubusercontent.com/279727/115973539-bf7cd600-a523-11eb-8a2a-b18138b462c6.png)

If you continue having trouble with that link, perhaps open a new issue?
