### ISSUE TITLE
Cannot get vtkMapper to vary radius and also apply vertex colors independently

### ISSUE THREAD

**Issue by timothyblue** [Kitware/vtk-js#940] opened 2018-11-01 20:49 UTC
In Vtk I can normally call `tubeMapper.SelectColorArray("Colors")` but this method does not exist in vtk.js

I am already using VARY_RADIUS_BY_ABSOLUTE_SCALAR so I cannot set the scalar values to be colors.

I have this so far but I cannot find a way to actually apply the color data I am supplying.

```
const colorData = new Float32Array(numPoints * 3);
    const colorArray = vtkDataArray.newInstance({
      name: 'Colors',
      values: colorData,
    });

for (let i = 0; i < nodeNumbers.length; i += 1) {
        const rgb = this.getVtkFromRgb(this.vizData.lookupStressColor(nodeNumbers[i], StressType.equivalent));
        colorData[3 * i] = rgb.r;
        colorData[(3 * i) + 1] = rgb.g;
        colorData[(3 * i) + 2] = rgb.b;
      }

polyData.getPointData().addArray(colorArray);
```

**Comment by dspring2** [comment] 2018-12-04 13:48
This comment is related to Issue https://github.com/Kitware/vtk-js/issues/953 and PR https://github.com/Kitware/vtk-js/pull/960

**Comment by jourdain** [comment] 2021-04-23 17:51
Closing duplicate of https://github.com/Kitware/vtk-js/issues/953

**Closed by jourdain** 2021-04-23 17:51 UTC
Labels: Status: Triage, Type: Feature Request 💡
