### ISSUE TITLE
Can't use @kitware/vtk.js with Jest

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/vtk-js#1990] opened 2021-07-08 12:14 UTC
### High-level description

@kitware/vtk.js seems to be built incorrectly, test frameworks such as Jest are unable to parse the package and throw an error.

I think the library should be compiled with ES5 as target (at least, for the `module` entry point), this way better interoperability will be provided.

### Steps to reproduce

1. Download the sample project [d8lhv.zip](https://github.com/Kitware/vtk-js/files/6784310/d8lhv.zip), or setup a Create React App and import any `@kitware/vtk.js` module from the package;
2. Add `"node_modules/(?!(@kitware)/)"` to the `transformIgnorePatterns` in package.json > jest
2. Create a test file and import `App.js`
2. Run `yarn test`

### Detailed behavior

Jest fails with the following error:

```
  FAIL  src/App.test.js
  ● Test suite failed to run

    /Users/federicozivolo/Downloads/d8lhv/node_modules/@kitware/vtk.js/Common/Core/Math.js: Cannot use import statement outside a module

      at interopRequire (node_modules/babel-plugin-macros/dist/index.js:86:15)
      at applyMacros (node_modules/babel-plugin-macros/dist/index.js:208:17)
      at ImportDeclaration (node_modules/babel-plugin-macros/dist/index.js:114:28)

```

### Expected behavior

Jest should be able to import the library without erroring.

### Environment
- **vtk.js**: 18.4.
- **OS**: macOS 11.4
- **Browser**: Node 12.20.0

**Comment by floryst** [comment] 2021-07-09 15:59
This is a result of `babel-plugin-macros` screwing with our `macro.js` file, since they assume that any files with `macro` (or ending in "macro.js"? I forget) should be parsed by them.

There are solutions using things like craco and other CRA customizations. I will work to update the docs on how to get around this, as well as consider any other alternatives to this unfortunate strange naming ownership debacle.

**Comment by FezVrasta** [comment] 2021-07-12 14:03
Thanks for the reply! It indeed seems to be a problem with Babel Plugin Macros.

Considering how popular the plugin is, would you consider to rename the file to something different?

**Comment by floryst** [comment] 2021-07-12 14:52
There are lots of projects that use this file, so it would be quite a breaking change to rename it. I am considering a solution that would not need a rename but would instead side-step babel-plugin-macros, but I need to test it first. Otherwise, we can consider a file rename, but I'm not going to take that route yet.

**Comment by FezVrasta** [comment] 2021-07-12 15:04
In order to keep backwards compatibility you could renam eit to `macros.js`, create a `macro.js` file that re-exports everything from `macros.js` and reference `macros.js` anywhere in the project.

**Comment by floryst** [comment] 2021-07-12 15:50
The issue unfortunately still stems from `babel-plugin-macros` expecting a valid macro in any file matching `/[./]macro(\.js)?$/`. I have a PoC approach where I do what you've stated, but (1) in cjs require syntax and (2) faking a macro so that babel-plugin-macros doesn't complain about seeing an invalid macro. I still need time to make this a build-time transform so that we don't have to maintain such a hack.

**Comment by floryst** [comment] 2021-07-12 21:43
Since there is a bug in `babel-plugin-macros` that affects the attempted fix, I'm more inclined to take your approach of migrating folks to using `macros.js` when necessary, and keeping a `macro.js` for backwards compat.

**Comment by FezVrasta** [comment] 2021-07-13 15:02
FYI I also opened an issue into the babel-plugin-macros repository to see if something can be done on their side.

https://github.com/kentcdodds/babel-plugin-macros/issues/178

**Comment by conartist6** [comment] 2021-07-13 15:23
`babel-plugin-macros` here: plugin-macros isn't meant to run on module code, which is what has been described happening in this issue. That is to say: the code in `node_modules` must be presumed to be node module code, not code which would be node module code if macros were evaluated.

Thus the problem is the way the jest configuration has been overridden as described by the original poster. Instead of using `transformIgnorePath` try this:
```
{
  "jest": {
    "transform": {
      "node_modules/@kitware/": "babel-jest"
    }
  }
}
```

**Comment by conartist6** [comment] 2021-07-13 15:33
I'm also curious about vtk's choice to have its `main` field point to `index.js`, which is an esmodule. I interpret that as being incorrect. Here are what the node docs say about the `main` field:

> The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module's exports object will be returned."

The other relevant bit of documentation says: "The CommonJS module require always treats the files it references as CommonJS"

That said, I don't think it's relevant here. All the tools involved are capable of reading `module` and should prefer it to `main`.

**Comment by floryst** [comment] 2021-07-13 15:48
> I'm also curious about vtk's choice to have its main field point to index.js, which is an esmodule. I interpret that as being incorrect. Here are what the node docs say about the main field:

Good point about the `main` field. That technically shouldn't be in the esmodule build's package.json, even though nobody ever does `require('vtk.js')` anyways. We typically import from subdirs inside vtk.js.

Thanks for the Jest config fix. It may work for the Jest case, but `babel-plugin-macros` still interferes when vtk.js consumers import `@kitware/vtk.js/macro.js`. After evaluating potential workarounds, it might be easier to switch to `macros.js`, keeping a `macro.js` for backwards compat. This may be a better approach long-term to avoid folks running into this issue in the future.

**Comment by conartist6** [comment] 2021-07-13 15:51
Ah yes, that would still be a problem. But fixing it would be as simple as providing an alias for `macro.js` that reexports from `macro.js`, right? Should work fine and be backwards compatible if a little messy...

**Comment by floryst** [comment] 2021-07-13 15:55
Yep, that would be the intended approach.

**Comment by conartist6** [comment] 2021-07-13 19:06
Ah ok. Yeah I didn't try running it. I think what you need is a custom transformer. Normally you would do it by editing the babel config with something like this:
```json
{
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```
Of course the problem with create-react-app is that it doesn't read a babel config file, instead constructing the config in scripts. But you aren't out of options! What you can do is something like this:

```json
/* package.json */
{
  "jest": {
    "transform": {
      "node_modules/@kitware/": "./module-transformer"
    }
  }
}
```

```js
// module-transformer.js

const { createTransformer } = require('babel-jest');

module.exports = createTransformer({
  plugins: ['transform-es2015-modules-commonjs']
});
```

**Comment by FezVrasta** [comment] 2021-07-14 07:10
> Of course the problem with create-react-app is that it doesn't read a babel config file, instead constructing the config object in scripts. But you aren't out of options! What you can do is something like this:

@conartist6 I tried what you suggested but it's still not working 😢

**Comment by conartist6** [comment] 2021-07-15 14:01
Did you run `jest --clearCache`?

**Comment by FezVrasta** [comment] 2021-07-15 15:18
> Did you run `jest --clearCache`?

Yes I did, it didn't help though.

**Comment by conartist6** [comment] 2021-07-15 15:48
What if you jam `"sourceType": "module"` into the transformer's babel options?

**Comment by FezVrasta** [comment] 2021-07-15 16:04
Still the same issue, I wonder if the fact `node_modules` is in the `transformIgnorePatterns` by default means that Jest is not applying the module-transformer on the library.

**Comment by conartist6** [comment] 2021-07-15 17:03
Yeah that would cause that error I'd think...

**Comment by FezVrasta** [comment] 2021-07-15 20:45
> Yeah that would cause that error I'd think...

But then if I remove kitware from the ignore list the CRA Babel config is applied 🤷‍♂️

**Comment by floryst** [comment] 2021-07-28 18:44
The name conflict should now be resolved in the latest version of vtk.js.

**Closed** 2021-08-25 15:15 UTC
Labels: type: bug 🐞, module: build
