### ISSUE TITLE
PaintWidget example error "_toConsumableArray$1 is not defined" with ES module build

### ISSUE THREAD

**Issue by gaston-perret** [Kitware/vtk-js#2117] opened 2021-10-14 16:21 UTC
### High-level description

Hello.
Im trying the PaintWidget example and is not working with the package @kitware/vtk.js
The error I get is 
Uncaught ReferenceError: _toConsumableArray$1 is not defined
    at 34ae905e-3a84-4278-a494-40a4a6cdceeb:616

That method is from Babel and is used in the file PaintFilter.worker.js 
May be some Babel config missing?
### Steps to reproduce

Installed and created project following https://kitware.github.io/vtk-js/docs/vtk_vanilla.html
Run the example PaintWidget https://kitware.github.io/vtk-js/examples/PaintWidget.html

### Environment
- **vtk.js**:  "@kitware/vtk.js": "^20.0.0"
- **OS**: Windows 10
- **Browser**:  Chrome 94 and Firefox 92

**Comment by floryst** [comment] 2021-10-14 16:34
See #2118. I think it should fix your problem.

**Comment by Guzzler** [comment] 2021-11-11 07:31
High-level description

Hello. Receiving the same issue as above.
Im trying the PaintWidget example and is not working with the package @kitware/vtk.js
The error I get is
Uncaught ReferenceError: _toConsumableArray$1 is not defined
at 34ae905e-3a84-4278-a494-40a4a6cdceeb:616

Still getting the same issue
Steps to reproduce

Installed and created project following https://kitware.github.io/vtk-js/docs/vtk_vanilla.html
Run the example PaintWidget https://kitware.github.io/vtk-js/examples/PaintWidget.html
Detailed behavior
Expected behavior
Environment

    vtk.js: "@kitware/vtk.js": "^20.4.2"
    OS: Ubuntu
    Browser:  Firefox 92


Are you sure this was fixed? If not is it possible to investigate @floryst

**Comment by davidborland** [comment] 2021-11-15 20:26
I am also still having this same problem:

Environment:
vtk.js: "@kitware/vtk.js": "^20.4.2"
OS: Built on Ubuntu, acessing webpage via Windows
Browser:  Chrome Version 95.0.4638.69 (Official Build) (64-bit)

The error appears to be coming from PaintFilter.worker.js

Note: I am using webpack v4 because I'm using create-react-app. Not sure if this could be related.

**Comment by floryst** [comment] 2021-11-15 20:58
Thanks for the reports. I will look into this.

**Comment by floryst** [comment] 2021-11-22 22:05
This should be fixed in #2172.

**Comment by davidborland** [comment] 2021-11-23 14:18
Great. Thanks for looking into it.

**Closed** 2021-12-09 21:37 UTC
Labels: type: bug 🐞, released
