### ISSUE TITLE
Positioning of vtkLabelWidget works improperly?

### ISSUE THREAD

**Issue by katiamar63** [Kitware/vtk-js#1142] opened 2019-07-11 13:44 UTC
In the example presented below, I use World Coordinates to set LabelWidgets   (the points are  picked by PointPicker from ImageSlice actor). You can see two rectangles containing labels created when slice is in different positions. 
When I change azimuth of camera, it seems that rendering labels on canvas is not proper (in one position the slice is under two clouds, after changing azimuth is in the middle).
Is translation worldsCoordinates->displayCoordinates done correctly?

![labels_problem](https://user-images.githubusercontent.com/3754848/61055384-5d3ef980-a3bf-11e9-9ec8-1d662f0f4e54.gif)

**Comment by luciemac** [comment] 2019-07-11 15:04
LabelWidget creates a canvas in a given context at a specific position.
For now, the position is the one computed in vtkPixelSpaceCallbackMapper.
My guesses are:
- maybe in labelWidget, in pixelSpace callback, camera should be used to set canvas position
- maybe in vtkPixelSpaceCallbackMapper, there is a problem when computing pixel position (probably camera parameters are not fully concidered ...)

**Comment by EmileSonneveld** [comment] 2019-10-07 10:59
I also have a positioning problem with `vtkLabelWidget`. When zooming on the web page, the label moves position. Mouse interaction still assumes the correct position, only the floating <canvas> is ofsetted.
Problem exists on version ^7.13.8 and version 11.4.2

**Comment by jourdain** [comment] 2019-10-07 13:28
The web page zooming issue is probably related to some css on that overlay canvas.

**Comment by EmileSonneveld** [comment] 2019-10-07 13:50
Hi @jourdain thanks for the quick response again :) 
The issue is also reproducible on the demo page:  https://kitware.github.io/vtk-js/examples/LabelWidget.html (In Chrome, FF, Edge)
When the page is zoomed, the user must move a widget by dragging with the mouse over the position where the label should be.
Explained in short video: https://www.dropbox.com/s/anx26wss5ft4c00/vtk_labels.mp4?dl=0

**Comment by mix3d** [comment] 2019-10-31 22:15
Why does the label widget draw a new canvas element? (sort of off topic) 
Wouldn't it be better to draw directly to the existing canvas?

**Comment by jourdain** [comment] 2019-10-31 22:21
You can not mix gl context and 2d context on the same canvas.

The new widgets infrastructure uses SVG representation rather than a canvas to draw text/lines.

**Comment by aylward** [comment] 2021-04-23 15:48
Duplicate (in part) with #1179    Also probably resolved with move to SVG for widgets

**Closed by aylward** 2021-04-23 15:48 UTC
Labels: Module: Interactor, Type: Bug 🐞
