### ISSUE TITLE
Rendering issues in iOS Safari

### ISSUE THREAD

**Issue by ty-ler** [Kitware/vtk-js#1938] opened 2021-05-26 16:51 UTC
### High-level description

I have ran into some weird rendering issues when using my company's web app DICOM viewer in iOS Safari. Things seem to render either dimmed or with significantly worse quality than on desktop browsers. macOS Safari does **NOT** have these issues.

### Steps to reproduce

* Using Safari on iOS 14.3
* Open MultiSliceImageMapper example from VTK.js documentation
* Compare iOS Safari result with a desktop browser (Google Chrome, Safari)

### Detailed behavior

These same problems are clear when looking at several examples from the VTK.js documentation page while using iOS Safari.

Examples which show the issue: 
https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html
https://kitware.github.io/vtk-js/examples/Cutter.html

### **Left:** Google Chrome on macOS; **Right:** Safari on iOS 14.3.
![image](https://user-images.githubusercontent.com/18401956/119697555-4cb29380-be1e-11eb-86b9-ccd0b5e05392.png)

### Expected behavior

iOS Safari should produce a result that is consistent with desktop browsers. With previous versions of iOS and/or VTK.js, I was not experiencing these same inconsistencies. 

### Environment
- **vtk.js**: 18.1.4
- **OS**: macOS 10.15.7, iOS 14.3
- **Browser**: Google Chrome, Safari (macOS), Safari (iOS)

**Comment by ljpearlman** [comment] 2021-08-01 00:54
I'm seeing the same behavior with Chrome and Safari on an iPhone Xs running ios 14.7.1.

**Comment by martinken** [comment] 2021-08-11 17:23
The issue is that on iOS 14 webgl no longer has support for interpolated float textures, see the issue here

https://developer.apple.com/forums/thread/675554

so while this worked in the past, it is now broken. We might be able to do a quick fix to use half float textures which are reported as still working in iOS 14 or an application can scale it's data down to unsigned char before passing it to the image mapper when running on iOS 14. I'll take a quick look to see how simple the half float change would be.

**Comment by martinken** [comment] 2021-08-11 17:24
e.g. the fallback on iOS 14 is unsigned char, so applications that are rendering images with larger data ranges will be impacted.

**Comment by martinken** [comment] 2021-08-11 17:58
Please give the following a try, it might work for you

https://github.com/Kitware/vtk-js/pull/2039

**Comment by ty-ler** [comment] 2021-08-11 18:51
> Please give the following a try, it might work for you
> 
> #2039

I think that did the trick. Things look normal again on iOS. Thanks!

**Comment by martinken** [comment] 2021-08-12 19:33
Please reopen if needed. Closing for now since it is merged.

**Closed by martinken** 2021-08-12 19:33 UTC
Labels: type: bug 🐞, module: rendering
