### ISSUE TITLE
ImageMarchingCubes changes polydata position

### ISSUE THREAD

**Issue by gaston-perret** [Kitware/vtk-js#2051] opened 2021-09-06 17:54 UTC
### High-level description

Hello. I'm having trouble using the filter ImageMarchingCubes and I might be dealing with a bug.

I'm using a VTI file as input for the filter ImageMarchingCubes and getting a polydata as intended.
The problem is that the polydata does not keep the XYZ position of the points that the imagedata had.

### Detailed behavior

We think this happens because the vti file Extent does not have the first components coordinates starting at 0.

After we correct the extent 0, 2 and 4 elements and we adjust the origin we get the correct position for the polydata. But this generates other problems.

I add an image showing the position difference:
![image](https://user-images.githubusercontent.com/66233297/132249771-990faae4-6b34-4bb8-9064-6fdb1131d459.png)

I will also attach the vti file we use as input for the IMC filter.
[mask2.zip](https://github.com/Kitware/vtk-js/files/7117341/mask2.zip)

To correct the position we change the extent and origin as follows:

`const mask = vtkImageData.newInstance()
      mask.shallowCopy(newValue.vti)

      const extent = mask.getExtent()
      const origin = mask.getOrigin()
      const spacing = mask.getSpacing()

      const newExtent = []
      const newOrigin = []

      newExtent[0] = 0
      newExtent[1] = extent[1] - extent[0]

      newExtent[2] = 0
      newExtent[3] = extent[3] - extent[2]

      newExtent[4] = 0
      newExtent[5] = extent[5] - extent[4]

      newOrigin[0] = origin[0] + spacing[0] * extent[0]
      newOrigin[1] = origin[1] + spacing[1] * extent[2]
      newOrigin[2] = origin[2] + spacing[2] * extent[4]

      mask.setExtent(newExtent)
      mask.setOrigin(newOrigin)`

### Expected behavior

Polydata output result of applying IMC filter to imagedata should respect the points XYZ coordinates
### Environment
- **vtk.js**:  19.0.4
- **OS**:  Windows 10 / Ubuntu
- **Browser**:  Chrome / Firefox

**Comment by jourdain** [comment] 2021-09-07 14:56
Is your ImageData oriented? How did you generate the polydata? Was it with vtk.js or VTK?

**Comment by gaston-perret** [comment] 2021-09-07 15:32
> 
> 
> Is your ImageData oriented? How did you generate the polydata? Was it with vtk.js or VTK?

I'm sorry but I don't know how to orient an ImageData. The polydata is the output result of the ImageMarchingCube filter and we are using vtk js.
But the vti used as input for the ImageMarchingCube is generated with VTK python.

**Comment by jourdain** [comment] 2021-09-07 15:40
I just checked and the image is axis aligned. The issue is indeed related to the extend not starting with 0 (which should be supported). 

The issue is that vtk.js does not properly position the volume rendering when extent do not start with a 0. 
@martinken

**Comment by gaston-perret** [comment] 2021-09-08 20:10
@jourdain we managed to solve the issues we were facing because of changing the imagedata's origin and extent. But the solution is a little rough. We could solve it more elegantly by doing a copy of the original vti. So we would mantain to vti, the original and another with the extent and origin corrected. So my question is, how do you do a complete copy of an imagedata?
something like newImageData = deepcopy(originalImageData)
I haven't seen a method like this.

**Comment by jourdain** [comment] 2021-09-08 20:14
```
const originalImageData = ...
const copyImage = vtkImageData.newInstance();
copyImage.shallowCopy(originalImageData);
```

**Comment by martinken** [comment] 2021-09-09 12:23
The MC filter in VTK is incorrect.  Specifically
```
    // Loop over all voxels, determine case and process
    const slice = dims[0] * dims[1];
    for (let k = 0; k < dims[2] - 1; ++k) {
      for (let j = 0; j < dims[1] - 1; ++j) {
        for (let i = 0; i < dims[0] - 1; ++i) {
```

I believe that needs to be

```
    const extent = input.getExtent();

    // Loop over all voxels, determine case and process
    const slice = dims[0] * dims[1];
    for (let k = extent[4]; k < extent[5]; ++k) {
      for (let j = extent[2]; j < extent[3]; ++j) {
        for (let i = extent[0]; i < extent[1]; ++i) {
```

Can you give that a try?

**Comment by martinken** [comment] 2021-09-09 12:54
OK I pushed a MR 2052. @gaston-perret  can you give it a try and see if it fixes your issues?

**Comment by gaston-perret** [comment] 2021-09-10 17:08
> 
> 
> OK I pushed a MR 2052. @gaston-perret can you give that MR a try and see if it fixes your issues?

Everything is working as expected. Thank you very much.
We will wait for the merge to master.
Thanks a lot!

**Comment by martinken** [comment] 2021-09-10 17:12
Merged. Thanks for checking to verify it worked!

**Closed by martinken** 2021-09-10 17:12 UTC
Labels: type: bug 🐞
