### ISSUE TITLE
Bounds computation with vtkImageSlice actor

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#284] opened 2017-07-17 14:50 UTC
I tried to display 3 slices (on each axis: X, Y and Z) from a vtkImageData, but I have some troubles with the clipping range. It seems that bounds of each actors is not right. (to inform you, I modified the OpenGL ImageMapper to define each slice and I use the origin of the vtkImageData). The next screenshot display 3 slices and the actor's outline (@jourdain advised it)  . Here is the result :
![image](https://user-images.githubusercontent.com/11785751/28273468-c577e1ce-6b0e-11e7-977e-efb89bcfc38d.png)

He thought that it could comes from OpenGL.
@martinken , do you have any ideas of what happens here ?

Here is some code :
```
     const imageMapperZ = vtkImageMapper.newInstance();
      imageMapperZ.setInputData(image);
      imageMapperZ.setZSliceIndex(0);
      this.imageActorZ = vtkImageSlice.newInstance();
      this.imageActorZ.setMapper(imageMapperZ);
      this.renderer.addActor(this.imageActorZ);

      const imageMapperY = vtkImageMapper.newInstance();
      imageMapperY.setInputData(image);
      imageMapperY.setYSliceIndex(0);
      this.imageActorY = vtkImageSlice.newInstance();
      this.imageActorY.setMapper(imageMapperY);
      this.renderer.addActor(this.imageActorY);

      const imageMapperX = vtkImageMapper.newInstance();
      imageMapperX.setInputData(image);
      imageMapperX.setXSliceIndex(0);
      this.imageActorX = vtkImageSlice.newInstance();
      this.imageActorX.setMapper(imageMapperX);
      this.renderer.addActor(this.imageActorX);

      const outlineX = vtkOutlineFilter.newInstance();
      outlineX.setInputData(this.imageActorX);
      const mapperX = vtkMapper.newInstance();
      mapperX.setInputData(outlineX.getOutputData());
      const actorX = vtkActor.newInstance();
      actorX.setMapper(mapperX);
      actorX.getProperty().setColor(0, 0, 1);
      this.renderer.addActor(actorX);

      this.renderer.resetCamera();
      this.renderer.resetCameraClippingRange();
      this.renderWindow.render();
```

**Comment by jourdain** [comment] 2017-07-26 18:48
@martinken 

The issue has nothing to do with bounds computation. It is related to invalid positioning of slices and volume in the 3D world.

Basically the outline geometry do render at the correct location while every mapper that deals with the vtkImageData are off. I'm wondering if you forget any translation after you've adjust the `orientation`.

**Comment by jourdain** [comment] 2017-07-26 18:50
By Volume, I mean Volume Rendering along with geometry. Mixing the Outline filter with any Volume Rendering should highlight the issue.

**Comment by martinken** [comment] 2017-07-26 18:54
Image or Volume? the above seems to be talking about image mappers as opposed to volume mapper. Is it both?

**Comment by jourdain** [comment] 2017-07-26 19:05
I think both have the same issue. But it is true that @laurennlam is only talking about image.

**Comment by jourdain** [comment] 2017-07-26 19:11
I'm talking about Volume Rendering as @scottwittenburg has seen similar alignment issue when trying to support volume rendering in ParaViewWeb with local rendering and vtk-js.

**Comment by martinken** [comment] 2017-07-26 19:20
I just check on an image example and it is working fine from what I can see  @laurennlam  has a modified version I believe which could be causing the issue.  I have not checked on the volume renderer though.   I'll try that next.

**Comment by martinken** [comment] 2017-07-26 19:20
If you have an example from vtk-js master that shows the image issue let me know.

**Comment by jourdain** [comment] 2017-07-26 19:23
Thanks @martinken, but not really it is on a branch which involve ParaView as server.

Adding the outline filter on any volume rendering example should be enough to validate it.

If there is no issue, then @scottwittenburg may have forgot to properly forward the `origin`, `spacing` of the dataset that he was transferring. (maybe)

**Comment by scottwittenburg** [comment] 2017-07-26 19:27
Well, I tried to set those properties:

https://github.com/Kitware/vtk-js/commit/62586b191835f31a17dc1bba9b9255366e9565b6

I haven't touched this in a couple months, so I'd have to dig back in to try and reproduce the issue.

**Comment by martinken** [comment] 2017-07-26 19:29
I just checked volumes as well with offsets and everything and it seems fine. Let me know if you continue to see issues on master and maybe I can help track it down.

**Comment by jourdain** [comment] 2017-07-26 19:29
Thanks @martinken, closing it for now then...

**Closed by jourdain** 2017-07-26 19:29 UTC

**Comment by laurennlam** [comment] 2017-08-18 09:56
Hi all,
Sorry for not replying to your comments. I couldn't work on it. But now, I'm back.
Now, I'm using the last version of the vtk.js (3.0.12), not a custom one.
I use one of the vtk.js data : headsq.vti
Here's the code I used to display one slice of the vti file:
```
/**
   * Load a vti as a volume and add it to the renderer
   * 
   * @param {string} url: url of the data
   * @param {function} callback: callback called when data is loaded
   */
  loadVTI(url, callback) {
    const reader = vtkHttpDataSetReader.newInstance({
          fetchGzip: true
    });
    reader.setUrl(url).then(() => {
      reader.loadData().then(() => {
        const data = reader.getOutputData();
        //data.getPointData().setActiveScalars('MetaImage');

        const imageMapper = vtkImageMapper.newInstance();
        imageMapper.setInputData(data);

        this.imageActorZ = vtkImageSlice.newInstance();
        this.imageActorZ.setMapper(imageMapper);

        this.renderer.addActor(this.imageActorZ);

        const outlineFilter = vtkOutlineFilter.newInstance();
        outlineFilter.setInputData(data);
        const mapper = vtkMapper.newInstance();
        mapper.setInputConnection(outlineFilter.getOutputPort());
        const actor = vtkActor.newInstance();
        actor.setMapper(mapper);
        this.renderer.addActor(actor);


        this.renderer.resetCamera();
        this.renderWindow.render();

        if(callback) {
          callback();
        }
      });
    });
  }
```

And here is the result I have when I display the outline and the slice : 
![image](https://user-images.githubusercontent.com/11785751/29453935-b145c2fa-840b-11e7-911c-3a7c4612b085.png)

@jourdain @martinken @scottwittenburg 
I don't know if I'm doing anything wrong or if it comes from somewhere in vtkjs code.
It seems that the origin and the size of the data are wrong, aren't they ?
What do you think ?

Thanks in advance for your response.

**Comment by jourdain** [comment] 2017-08-18 15:17
Is your PR with the `model.bound` change fix that issue?

**Comment by laurennlam** [comment] 2017-08-21 07:19
@jourdain unfortunately no.

**Comment by laurennlam** [comment] 2017-08-21 07:49
I didn't have time to check it last friday. But, it seems to work better now:
![image](https://user-images.githubusercontent.com/11785751/29508602-6e9189fc-8655-11e7-829f-28a36e1bbe84.png)

![image](https://user-images.githubusercontent.com/11785751/29508667-a0305376-8655-11e7-952e-f201f459af7b.png)
