### ISSUE TITLE
vtkClipClosedSurface interface: When the intercept plane is larger than 2, the efficiency is very very slow

### ISSUE THREAD

**Issue by xut-d** [Kitware/vtk-js#2570] opened 2022-09-09 02:34 UTC
### Need
When I tried to intercept 5 planes with same geometry  for vtkClipClosedSurface interface,  it took ten times as long as two planes.

### Feature

This function is very important for us, and we hope to improve the efficiency to two planes when we intercept five planes.
![origin_img_v2_fb5584c2-0563-4961-81f0-f04062423b2g](https://user-images.githubusercontent.com/84498316/189260303-fe2f0b4e-6f4e-4f22-90b2-9e46d00a32cd.jpg)

**Comment by chenyuzheng** [comment] 2022-09-09 03:03
We also encountered the same problem, now also do not know how to solve

**Comment by finetjul** [comment] 2022-09-09 08:10
Can you profile (in the Performance tab) the algorithm to identify the bottleneck ?

**Comment by xut-d** [comment] 2022-09-13 08:46
Hi, This is what we got here from the performance tab, Do you know why this line(561) of code is taking so long?  
![origin_img_v2_2fdcf2fb-8107-489c-814c-5059507af14g](https://user-images.githubusercontent.com/84498316/189855678-f7d487ff-85ba-41f4-906e-5da5989b3b55.jpg)
![origin_img_v2_ddf24106-0e8c-4d7b-9df0-7f81c7d8cbdg](https://user-images.githubusercontent.com/84498316/189855712-ae481ee7-6c83-4ae5-8c5f-b6a0950afd09.jpg)

**Comment by finetjul** [comment] 2022-09-14 06:11
I don't see how this function can be significantly speeded. 
This "slow" behavior is likely to be the same in c++

**Comment by xut-d** [comment] 2022-09-14 06:59
C++ uses the same interface and data to accomplish this function, which is significantly faster by several levels, almost all in milliseconds. Do you know why this line of code takes so long？thank you!
![image](https://user-images.githubusercontent.com/84498316/190082488-5398e908-6d55-4e70-a3b3-661c59475f27.png)

**Comment by finetjul** [comment] 2022-09-14 09:07
I doubt the bottleneck comes from this line in particular, the issue is that it is 3 nested for loops, hence it is slow.
You might want to try a different web browser (firefox, edge...) to do the profiling. This might just be a sampling issue.

**Comment by chenyuzheng** [comment] 2022-10-12 08:48
May I ask how to solve the above efficiency problem? My team also encountered the same problem, or is there a similar alternative interface? If so, are there relevant examples?

**Comment by finetjul** [comment] 2022-10-12 11:31
Would you mind sharing with me your dataset + planes ?

**Comment by chenyuzheng** [comment] 2022-10-13 07:35
[1.zip](https://github.com/Kitware/vtk-js/files/9771936/1.zip)
Here is my planes:
const planes = [];
const plane1 = vtkPlane.newInstance({
  origin: [70.17235662874292, 11.82385193639344, -363.6235551457101],
  normal: [0.07643856104746827, -0.005788522725215297, 0.997057490513788],
});
planes.push(plane1);
const plane2 = vtkPlane.newInstance({
  origin: [69.91117370004254,-9.658953141545462,-353.92941931722913],
  normal: [0.07692580284009085, 0.8838848485683667,0.46133501420191697],
});
planes.push(plane2);
const plane3 = vtkPlane.newInstance({
  origin: [69.91117370004254,-9.658953141545462,-353.92941931722913],
  normal: [0.012514208525830644,0.9179061151095466,-0.39660025016314826],
});
planes.push(plane3);
const plane4 = vtkPlane.newInstance({
  origin: [71.19630880054876,25.028792194165522,-358.3598991217545],
  normal: [0.05765567434663872,-0.3213691230602294,0.9451971804650781]
});
planes.push(plane4);
const plane5 = vtkPlane.newInstance({
  origin: [71.19630880054876,25.028792194165522,-358.3598991217545],
  normal: [-0.0078469453868405,-0.8960256144165654,0.4439330171968656]
});
planes.push(plane5);

**Comment by finetjul** [comment] 2022-10-13 22:44
Few things:
 - do not use STL, it duplicates points. The VTK.js implementation is currently missing the [MergingPoints](https://gitlab.kitware.com/vtk/vtk/-/blob/b4f8df44af045dc0960e63a5f26aee949d44259c/IO/Geometry/vtkSTLReader.cxx#L159-204) functionality. You can contribute that functionality, or use the VTP file format 
 - your first clipping plane should be the one that clips as much as possible the bone cells. (reorder the planes in your example)
 - there are some bugs, #2601  improves things but is not ready yet.

**Comment by finetjul** [comment] 2022-10-25 20:03
Please note that #2601 is now complete and improves performances dramatically (granted that points were merged beforehand)

**Closed** 2022-10-30 21:14 UTC
Labels: module: filters, type: performance ⚡️

**Comment by xut-d** [comment] 2022-11-30 01:48
We‘ll verify it soon，Thank you very much for your answer.
